class DatabaseConstants:
    USER_EMAIL_MAX_LENGTH = 255
    USER_NAME_MAX_LENGTH = 255
    USER_PASSWORD_MAX_LENGTH = 255
    USER_ROLE_MAX_LENGTH = 50

    RECORD_CATEGORY_MAX_LENGTH = 100
    RECORD_TYPE_MAX_LENGTH = 50
    RECORD_NOTES_MAX_LENGTH = 1000

    AMOUNT_PRECISION = 15
    AMOUNT_SCALE = 2


class ValidationConstants:
    PASSWORD_MIN_LENGTH = 8
    PASSWORD_MAX_LENGTH = 128

    FULL_NAME_MIN_LENGTH = 2
    FULL_NAME_MAX_LENGTH = 100

    NOTES_MAX_LENGTH = 1000
    CATEGORY_MAX_LENGTH = 100

    AMOUNT_MIN = 0.01

    QUERY_STRING_MAX_LENGTH = 100

    DEFAULT_PAGE_SIZE = 20
    MAX_PAGE_SIZE = 100
    MAX_RECENT_RECORDS = 50
    DEFAULT_TREND_MONTHS = 6


class AuthConstants:
    BEARER_SCHEME = "Bearer"
    TOKEN_TYPE = "bearer"
